trainingset <- read.delim("~/Documents/Documents/School/Fall 2015/Biol 2430 - Casey/d3-project/trainingsetPre.txt")
trainingset <- subset(trainingset, spop1==1)
trainingset <- subset(trainingset, select= -c(spop2, spop3, freq1, freq2, freq3, physPos))
trainingset <- subset(trainingset, select= -c(spop1))
trainingset <- subset(trainingset, select= -c(stime, scoeff, sfreq, hdom, mutRate, recRate, origins))
trainingset <- subset(trainingset, select= -c(DAF_2, DAF_3, MAF_2, MAF_3, DDAF_2, DDAF_3, FST_2, FST_3))
trainingset <- subset(trainingset, select= -c(ThetaPi_2, ThetaPi_3, ThetaS_2, ThetaS_3, ThetaH_2, ThetaH_3, ThetaL_2, ThetaL_3, ThetaXi_2, ThetaXi_3))
trainingset <- subset(trainingset, select= -c(TajD_2, TajD_3, FuLiF_2, FuLiF_3, FuLiD_2, FuLiD_3, FayWuH_2, FayWuH_3, ZengE_2, ZengE_3))
trainingset <- subset(trainingset, select= -c(Theta1Pi_2, Theta1Pi_3, Theta1S_2, Theta1S_3, Theta1H_2, Theta1H_3, Theta1L_2, Theta1L_3, Theta1Xi_2, Theta1Xi_3))
trainingset <- subset(trainingset, select= -c(TajD1_2, TajD1_3, FuLiF1_2, FuLiF1_3, FuLiD1_2, FuLiD1_3, FayWuH1_2, FayWuH1_3, ZengE1_2, ZengE1_3))
trainingset <- subset(trainingset, select= -c(ZA_2, ZA_3, H1_2, H1_3, H2_2, H2_3, H12_2, H12_3, H2.H1_2, H2.H1_3))
trainingset <- subset(trainingset, select= -c(iHH1_2, iHH1_3, iHH0_2, iHH0_3, SL1_2, SL1_3, SL0_2, SL0_3))
trainingset <- subset(trainingset, select= -c(iHS_2, iHS_3, DiHH_2, DiHH_3, nSL_2, nSL_3, DnSL_2, DnSL_3, XPEHH_23, DXPEHH_23))
# trainingset <- subset(trainingset, select= -c(MAF_1, Theta1Pi_1, Theta1S_1, Theta1H_1, Theta1L_1, Theta1Xi_1, TajD1_1, FuLiF1_1, FuLiD1_1, FayWuH1_1, ZengE1_1, iHH1_1, iHH0_1, SL1_1, SL0_1))
trainingset <- rbind(subset(trainingset, sclass=="ne"), subset(trainingset, sclass=="hs"), subset(trainingset, sclass=="hl"), subset(trainingset, sclass=="ss"), subset(trainingset, sclass=="sl"))
View(trainingset)
write.table(trainingset, "~/Documents/Documents/School/Fall\ 2015/Biol\ 2430\ -\ Casey/d3-project/trainingsetPost.txt", sep="\t", quote=FALSE, row.names=FALSE)
